services:

  ollama:
    build: ollama
    ports: 
      - 11434:11434
    volumes:
      - tutorial-vol:/ollama
    entrypoint: ["usr/bin/bash", "/pull-ollama.sh"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false

volumes:
  tutorial-vol:
    driver: local
  
